### ISSUE TITLE
alpine support

### ISSUE THREAD

**Issue by willfarrell** [mvanholsteijn/strip-docker-images#12]
`/mybin/strip-docker-image-export: line 142: /usr/bin/dpkg: No such file or directory`

**Comment by mvanholsteijn** [comment]
Unfortunately I do not have Alpine support included.

**Comment by agrrh** [comment]
I would like to propose such: https://github.com/mvanholsteijn/strip-docker-image/pull/14

**Comment by mvanholsteijn** [comment]
merged
